name: test_assignment
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  flutter_bloc: 8.1.3
  retrofit: 4.0.3
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  logging: 1.2.0
  get_it: 7.6.6
  injectable: 2.3.2
  go_router: 13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.3.3
  retrofit_generator: 8.0.6
  json_serializable: 6.7.1
  freezed: 2.4.6
  injectable_generator: 2.4.1
  go_router_builder: 2.4.1

flutter:
  uses-material-design: true
  fonts:
    - family: "SF Pro Display"
      fonts:
        - asset: assets/fonts/sf_pro_display/medium.otf
          weight: 500
        - asset: assets/fonts/sf_pro_display/semibold.otf
          weight: 600
        - asset: assets/fonts/sf_pro_display/regular.otf
          weight: 400
